services:
  - type: web
    name: image-stego-python
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    region: oregon
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
